# Generated by Django 6.0.3 on 2026-03-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
                ('category_name', models.CharField(max_length=50)),
                ('total_rentals', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'category_performance',
            },
        ),
        migrations.CreateModel(
            name='FilmModelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('model_file', models.CharField(max_length=255)),
                ('training_data', models.CharField(max_length=255)),
                ('training_date', models.DateTimeField()),
                ('model_summary', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FilmPopularity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('rental_count', models.IntegerField(default=0)),
                ('rating', models.CharField(max_length=10)),
                ('rental_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'film_popularity',
            },
        ),
    ]
